declare const styles: {
  readonly mainWrapper: string;
  readonly boardContainer: string;
  readonly machineLabelsColumn: string;
  readonly machineLabelsHeader: string;
  readonly machineLabelsScroll: string;
  readonly machineLabel: string;
  readonly machineLabelId: string;
  readonly machineLabelArea: string;
  readonly timelineScrollArea: string;
  readonly timeAxisHeader: string;
  readonly timeAxisContent: string;
  readonly gridLine: string;
  readonly gridLineMajor: string;
  readonly gridLineMinor: string;
  readonly timeLabel: string;
  readonly timelineRowsScroll: string;
  readonly schedulingBoardTimeline: string;
  readonly fullGridLine: string;
  readonly fullGridLineMajor: string;
  readonly fullGridLineMinor: string;
  readonly timelineRow: string;
  readonly rowContent: string;
  readonly downtimeSlot: string;
  readonly downtimeIcon: string;
  readonly downtimeText: string;
  readonly downtimeTime: string;
  readonly orderCard: string;
  readonly orderCardScheduled: string;
  readonly orderCardPending: string;
  readonly orderCardDragging: string;
  readonly orderCardTop: string;
  readonly orderCardBottom: string;
  readonly fullscreenButton: string;
  readonly fullscreenButtonText: string;
};

export default styles;
